# --- DEPENDENCIAS ---
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
NUTRITION_COACH_APP_DIR = BASE_DIR / "nutrition_coach_flask_app"
NUTRITION_COACH_TEMPLATES_DIR = NUTRITION_COACH_APP_DIR / "templates"
NUTRITION_COACH_STATIC_DIR = NUTRITION_COACH_APP_DIR / "static"
NUTRITION_COACH_EXAMPLES_DIR = NUTRITION_COACH_STATIC_DIR / "examples"
NUTRITION_COACH_DEFAULT_MODEL = "llama3.2-vision"
NUTRITION_COACH_SUPPORTED_MODELS = (
    "llama3.2-vision",
    "llava",
    "qwen2.5vl:3b",
)
NUTRITION_COACH_IMAGE_SIZE = (128, 128)
NUTRITION_COACH_SIMILARITY_THRESHOLD = 0.84
NUTRITION_COACH_DEFAULT_QUERY = "How many calories are in this food?"
NUTRITION_COACH_SECRET_KEY = "nutrition-coach-demo-key"
NUTRITION_COACH_HOST = "127.0.0.1"
NUTRITION_COACH_PORT = 5000
