# --- DEPENDENCIAS ---
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
STYLE_FINDER_APP_DIR = BASE_DIR / "style_finder_fashion_rag_app"
STYLE_FINDER_EXAMPLES_DIR = STYLE_FINDER_APP_DIR / "examples"
STYLE_FINDER_OUTPUTS_DIR = STYLE_FINDER_APP_DIR / "outputs"
STYLE_FINDER_DEFAULT_MODEL = "llama3.2-vision"
STYLE_FINDER_SUPPORTED_MODELS = (
    "llama3.2-vision",
    "llava",
    "qwen2.5vl:3b",
)
STYLE_FINDER_SIMILARITY_THRESHOLD = 0.82
STYLE_FINDER_TOP_ALTERNATIVES = 3
STYLE_FINDER_MAX_TOTAL_ALTERNATIVES = 10
STYLE_FINDER_IMAGE_SIZE = (128, 128)
STYLE_FINDER_GRADIO_HOST = "127.0.0.1"
STYLE_FINDER_GRADIO_PORT = 5000
